---


# contextNonInteractiveRules
# contextBashRcFilePaths

- name: Add non-interactive rule to .bashrc file
  become: true
  lineinfile:
    path: "{{ contextBashRcFilePath }}"
    state: present
    insertafter: '^#NON-INTERACTIVE$'
    line: "{{ nonInteractiveRuleItem }}"
  loop: "{{ (contextNonInteractiveRules is string)|ternary([contextNonInteractiveRules],contextNonInteractiveRules|reverse|list) }}"
  loop_control:
    loop_var: nonInteractiveRuleItem


...