---

##
#
# Required:
# contextSystemUsername
# contextHomeDirectory
#
# Optional:
# contextUserPaths
# contextNonInteractiveRules
# contextInteractiveRules
# [contextRemoveExistingFile]

#- name: Remove existing .bashrc file
#  when: contextRemoveExistingFile|default(no)
#  become: true
#  file:
#    path: "{{ contextHomeDirectory }}/.bash_profile"
#    state: absent 

- name: Generate .bashrc configuration
  when: ansible_facts['distribution'] == 'Ubuntu'
  become: true
  block:
    - name: Generate .bashrc configuration
      template:
        src: bashrc/bash.profile.j2
        dest: "{{ contextHomeDirectory }}/.bash_profile"
        owner: "{{ contextSystemUsername }}"
        group: "{{ contextSystemUsername }}"
        mode: 0640
        force: true
    - template:
        src: bashrc/bashrc.ubuntu.j2
        dest: "{{ contextHomeDirectory }}/.bashrc"
        owner: "{{ contextSystemUsername }}"
        group: "{{ contextSystemUsername }}"
        mode: 0640
        force: true

- name: Generate .bashrc configuration
  when: 
    - "'id' in ansible_facts['lsb']"
    - ansible_facts['lsb']['id'] == 'Raspbian'
    - ansible_facts['distribution_major_version']|int >= 10
  become: true
  block:
    - name: Generate .bashrc configuration
      template:
        src: bashrc/bash.profile.j2
        dest: "{{ contextHomeDirectory }}/.bash_profile"
        owner: "{{ contextSystemUsername }}"
        group: "{{ contextSystemUsername }}"
        mode: 0640
        force: true
    - template:
        src: bashrc/bashrc.raspbian10.j2
        dest: "{{ contextHomeDirectory }}/.bashrc"
        owner: "{{ contextSystemUsername }}"
        group: "{{ contextSystemUsername }}"
        mode: 0640
        force: true

- name: Generate .bashrc configuration
  when: 
    - ansible_facts['distribution'] == 'CentOS'
    - ansible_facts['distribution_major_version'] == '8'
  become: true
  block:

    - name: Generate .bashrc configuration
      template:
        src: bashrc/bash.profile.j2
        dest: "{{ contextHomeDirectory }}/.bash_profile"
        owner: "{{ contextSystemUsername }}"
        group: "{{ contextSystemUsername }}"
        mode: 0640
        force: true
    - template:
        src: bashrc/bashrc.centos8.j2
        dest: "{{ contextHomeDirectory }}/.bashrc"
        owner: "{{ contextSystemUsername }}"
        group: "{{ contextSystemUsername }}"
        mode: 0640
        force: true

...